var firstName="Raghupati";
console.log(firstName);
console.log(typeof firstName);
var age=32;
console.log(age);
console.log(typeof age);
var isMarried=true;
console.log(isMarried);
console.log(typeof isMarried);
var city="Pune";
city=50000;
console.log(typeof city);
console.log('=============================');
var salary=null;
console.log(typeof salary);
salary=40000.50;
var typeOfSalary=typeof salary;
console.log("Salary=>",salary,'typeof salary=>',typeOfSalary );
salary="Forty Thousand";
var salaryTypeOf=typeof salary;
console.log('salary=>',salary,'typeof=>',salaryTypeOf);